import { jsPDF } from 'jspdf';
import { UkscItem, BillDetails } from '../types';

export const generateBillPDF = (uksc: UkscItem, bill: BillDetails) => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(41, 128, 185); // Blue
  doc.rect(0, 0, 210, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.text('Electricity Bill Details', 20, 25);

  // Bill Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  
  let y = 60;
  const lineHeight = 10;

  doc.setFont('helvetica', 'bold');
  doc.text('Property / Tenant Details', 20, y);
  y += lineHeight;
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text(`Tenant Name: ${uksc.tenant.name || 'N/A'}`, 20, y);
  y += lineHeight;
  doc.text(`Flat/Plot No: ${uksc.tenant.flatOrPlotNo || 'N/A'}`, 20, y);
  y += lineHeight;
  doc.text(`Phone: ${uksc.tenant.phone || 'N/A'}`, 20, y);
  y += lineHeight;
  doc.text(`UKSC Number: ${uksc.ukscNumber}`, 20, y);
  
  y += 20;

  // Payment Details
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('Bill Summary', 20, y);
  y += lineHeight;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text(`Bill Date: ${bill.billingDate}`, 20, y);
  y += lineHeight;
  doc.text(`Due Date: ${bill.dueDate}`, 20, y);
  y += lineHeight;
  doc.text(`Units Consumed: ${bill.unitsConsumed}`, 20, y);
  y += lineHeight;
  doc.text(`Status: ${bill.status}`, 20, y);
  y += lineHeight + 5;
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total Amount: ₹${bill.amount}`, 20, y);

  // Footer
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by PowerBill Manager App', 20, 280);

  doc.save(`Bill_${uksc.ukscNumber}_${bill.billingDate}.pdf`);
};
